### ISSUE TITLE
Check programs and scripts needed for running bedboss

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedboss#1]
Feel free to add your comments, propositions, and issues in bedboss

1) Programs that need to be installed before running **bedqc**:

- [X] None

2) Programs that need to be installed before running **bedmaker**:

- [ ] bedToBigBed
- [ ] BigBedToBed
- [ ] ... and other similar programs
- [ ] Refgenome of different assemblies than hg38, hg19, and mm

3) Programs that need to be installed before running **bedstat**:

- [ ] R
- [ ] GenomicDistributions
- [ ] GenomicDIstribution data
- [ ] ... ?

**Comment by nsheff** [comment]
This should all end up in a bulker crate for bedboss.

**Comment by khoroshevskyi** [comment]
All required dependencies can be checked by running this script: https://github.com/bedbase/bedboss/blob/6f10c0a0cff3cfeafd5aed7f1cbc2dc634445cda/test/bash_requirements_test.sh.

Other, not required dependencies are checked while running pipelines, and if some of them are not provided, then bedboss will download them
