### ISSUE TITLE
R package check is broken

### ISSUE THREAD

**Issue by nsheff** [databio/bedboss#12]
there's a installation check script that ensures I can run the pipelines. But, it doesn't work. Look, it says R packages are all successful, when I don't even have R installed

![image](https://github.com/databio/bedboss/assets/5271009/fc5045dc-7e1b-444a-acae-6bdcb0dd59c7)

**Comment by khoroshevskyi** [comment]
If you will install R, then all this R packages check will fail, if you don't have them installed.

**Comment by nsheff** [comment]
... which doesn't make sense :). This is not super high priority, but something we should fix maybe in the next round.

**Comment by khoroshevskyi** [comment]
Fixed in 0.1.0a3
