### ISSUE TITLE
Bedboss: Consolidating bedbase pipeline components

### ISSUE THREAD

**Issue by nsheff** [databio/bedboss#54]
Right now there are lots of pipeline components that go in to ingesting BED files into bedbase. These include: bedqc, bedstat, bedembed, bedmaker.

In conversation with @Khoroshevskyi, we wondered if it wouldn't make sense to integrate some or all of these functions into a single pipeline. @xuebingjie1990 do you have any comments? you're the most experienced here. Or, maybe @joseverdezoto.

**Comment by khoroshevskyi** [comment]
I had discussion this problem with @xuebingjie1990. I think we cand combine all this pipelines but we should improve and refactor all of them to have possibility use them in Python (as Python API). 
I am looking for further discussion:)

**Comment by khoroshevskyi** [comment]
this issue is solved
