### ISSUE TITLE
Switching the CLI from an argument-based parameterization to a config-based parameterization

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedboss#6]
Consider switching the CLI from an argument-based parameterization to a config-based parameterization, given the number of parameters that are required for this process.

**Comment by nsheff** [comment]
I would be fine with that.

**Comment by khoroshevskyi** [comment]
We simplified that process. Now you can run insert function as Python  API and CLI. Additionally insert receives pep and loops through each sample to calculate statistics.
This issue is outdated.
