### ISSUE TITLE
integrate populator repository

### ISSUE THREAD

**Issue by nsheff** [databio/bedboss#72]
Related to databio/bedhost#93 

I think the actions and scripts in [bbuploader](https://github.com/databio/bbuploader) would be easier to manage if they were a subfolder in this repository.

@khoroshevskyi not sure if you agree here, though.

**Comment by nsheff** [comment]
Related to: https://github.com/databio/bedbase/issues/53

**Comment by khoroshevskyi** [comment]
For now, I would keep it separate, as it's still under development, but after it will be finished we can decide if we want to move it to bedbase or should it stay here
